### ISSUE TITLE
Using runtime RenderTexture

### ISSUE THREAD

**Issue by LelouBil** [Cyanilux/URP_BlitRenderFeature#13]
Hello, I am using a Render Texture that is generated at runtime when the resolution of the screen changes (I think it is better to render at the native resolution and not above since it will be full screen).

At first, I was using a canvas and a Raw Image, but that didn't feel like the correct way to put the Render Texture onto the screen.

Then I found about this, and It works perfectly with an asset Render Texture but if I change it at runtime unity complains about “Type Mismatch”.
I think it's because the URP Renderer is an asset, and I'm trying to make it reference something that is not an asset.

How can use a runtime Render Texture as a source ?

**Comment by lgarczyn** [comment]
I think you're confusing what this package is used for.

The idea is to replace the old ImageEffect texture system, where you receive your rendered screen as a texture, modify it using a material/shader, and then display it again, using a quad sized exactly to your screen.

This was used before URP to make effects like vignettes, volumetric clouds, etc. This project is simply there to use legacy systems with URP.

Fundamentally, the only part of this project you would want to use is the last one: creating a quad with the correct size with a render texture as the source.

Which is exactly what rawimage would allow you to do.
