### ISSUE TITLE
Package installation fails with URP 14.0.3 and unity 2022.2.0b10

### ISSUE THREAD

**Issue by lgarczyn** [Cyanilux/URP_BlitRenderFeature#14]
Tried to add ECS to my project, upgraded URP and unity

Sadly whenever the package manager tries to install BitRenderFeature, it fails with this error

```
[Package Manager Window] Error adding package: com.cyanilux.urp-blitrenderfeature@https://github.com/Cyanilux/URP_BlitRenderFeature.git.
ENOTEMPTY: directory not empty, rmdir 'pojectdir\Library\PackageCache\.tmp-13968-EFB7LJGCNbRz'
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

```

**Comment by lgarczyn** [comment]
Copying the files directly in the folder works normally

**Comment by Cyanilux** [comment]
This error seems related to the Package Manager itself or a bug introduced in that beta version of Unity, not something I can fix.
Could try deleting that directory and let Unity repopulate it. Probably a good idea to back-up before that just in case.
But if copying files manually works, that's good too.

**Comment by lgarczyn** [comment]
Deleting this file or even the whole library does nothing. Will try to reproduce the big with another package
