### ISSUE TITLE
Fixing obsolete and deprecated warnings using RTHandle

### ISSUE THREAD

**Issue by lgarczyn** [Cyanilux/URP_BlitRenderFeature#15]
I get the following warning on compile:

> 'RenderTargetHandle' is obsolete: 'Deprecated in favor of RTHandle'

> 'ScriptableRenderPass.Blit(CommandBuffer, RenderTargetIdentifier, RenderTargetIdentifier, Material, int)' is obsolete: 'Use RTHandles for source and destination' 

> 'ScriptableRenderer.cameraColorTarget' is obsolete: 'Use cameraColorTargetHandle' 

The last one is easy to fix, simply switching to "cameraColorTargetHandle" works.

Changing m_TemporaryColorTexture and m_DestinationTexture are similarly easy, following this guide:

https://forum.unity.com/threads/rendertargethandle-is-obsolete-deprecated-in-favor-of-rthandle.1211052/

But any further change proved extremely hard to fix and debug.

**Comment by Cyanilux** [comment]
I've uploaded a [2022.1 branch](https://github.com/Cyanilux/URP_BlitRenderFeature/tree/2022.1) which uses the newer RTHandle and Blitter API, based on experiments I've done previously.
It still has some issues as listed in the readme. Notably it requires a specific vertex shader (includes BlitExample.shader as an example) - also means it won't work with shader graphs anymore which I don't like, but maybe that'll change when the Fullscreen graph is properly introduced. (Not going to mess around with Unity beta versions atm)

**Comment by lgarczyn** [comment]
Thank you so much! I'm also excited for the Fullscreen graph node, but I understand that developing for the beta doesn't make sense for you.

This is for a normal shader, so no problem on my side.
