### ISSUE TITLE
cmd-drawMesh and depth texture

### ISSUE THREAD

**Issue by BruceKristelijn** [Cyanilux/URP_BlitRenderFeature#17]
I just tried switching to cmd-drawMesh but can't figure out how to get the depth texture.  It seems that the screenmesh is included somehow?

**Comment by Cyanilux** [comment]
Hmm, perhaps make sure the shader used by the feature has `ZWrite Off`?
(If it's a graph there should be an option for that in the Graph Settings (in 2021.2+ at least). Or use Transparent surface mode)

**Comment by BruceKristelijn** [comment]
I made sure to turn that off. It's odd shader worked on the 2022 and the master branch. Just found your shadergraph [example](https://github.com/Cyanilux/URP_BlitRenderFeature/blob/cmd-drawMesh/Examples/BlitReconstructDepthBlit.shadergraph). This seems to do what I need. I will try to turn this into a regular shader.
