### ISSUE TITLE
ScriptableRenderPass.Blit has been deprecated with 2023.x

### ISSUE THREAD

**Issue by kayroice** [Cyanilux/URP_BlitRenderFeature#19]
Looks like *ScriptableRenderPass.Blit* is no longer supported with 2023.x. I just tried upgrading to [2023.1.8](https://unity.com/releases/editor/whats-new/2023.1.8) (*URP-15.0.6*) from 2022.3.7 (*URP-14.0.8*), and am getting the following error message starting on line [115](https://github.com/Cyanilux/URP_BlitRenderFeature/blob/751e97de92157f21ee184377188c71aed5c6de92/Blit.cs#L113) in the *Execute* method of *URP_BlitRenderFeature/Blit.cs*:

```
ScriptableRenderPass.Blit(...) is obsolete: 'Use RTHandles for source and destination'
```

*ScriptableRenderer.cameraColorTarget*, and *RendererTargetHandle* have been marked as deprecated as well, but aren't yet throwing an error.

**Comment by kayroice** [comment]
Found a thread about upgrading from *RendererTargetHandle* to *RTHandles* here:

['RenderTargetHandle' is obsolete: 'Deprecated in favor of RTHandle'](https://forum.unity.com/threads/rendertargethandle-is-obsolete-deprecated-in-favor-of-rthandle.1211052)

This doc in particular talks about upgrading to *RTHandles*:

[Upgrading to version 2022.1 of the Universal Render Pipeline](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@13.1/manual/upgrade-guide-2022-1.html)

Haven't found anything about how to deal with upgrading from *ScriptableRenderPass.Blit* yet, unfortunately.

**Comment by kayroice** [comment]
Haven't found a solution yet for upgrading from *ScriptableRenderPass.Blit*, but according to this [thread](https://forum.unity.com/threads/how-to-blit-in-urp-documentation-unity-blog-post-on-every-blit-function.1211508/) it sounds like the direction to go might be to use [Blitter](https://docs.unity3d.com/Packages/com.unity.render-pipelines.core@15.0/api/UnityEngine.Rendering.Blitter.html).

**Comment by Cyanilux** [comment]
Heya, the repo already has a 2022.1 branch which makes use of the Blitter API. See : https://github.com/Cyanilux/URP_BlitRenderFeature/tree/2022.1

If you just need to apply materials to the screen (camera source & destination) URP 2022.2+ also now provides a Fullscreen Pass Renderer Feature already, which is used with the new Fullscreen Graph (or a code shader similar to the one in that 2022.1 branch)

**Comment by kayroice** [comment]
Oh awesome, thanks for the quick response! I'll just try the *2022.1* branch, and let you know how it goes with *Unity 2023.1* and *URP-15.0.6* since you're using *Blitter*. But thanks for the heads up on the *Fullscreen Pass Renderer Feature*. I noticed they released that a while ago, but didn't pay much attention since I was already using your code which is working perfectly for my use case (thanks!).

Any idea when you'll be merging your *2022.1* branch into *master*?

**Comment by Cyanilux** [comment]
> Any idea when you'll be merging your _2022.1_ branch into _master_?

Not sure. If I merge it'll probably break the script for older versions if users try to use the update button in the Package Manager (maybe if I add the "unity" version to the manifest json that won't appear? idk)

Also since 2022.2+ has it's own feature I somewhat see my BlitRenderFeature as obsolete now.

So might just leave it as is. If you want to install the 2022.1 branch specifically you can always use `https://github.com/Cyanilux/URP_BlitRenderFeature.git#2022.1` in the package manager, or copy the files manually.
