### ISSUE TITLE
Single pass VR Support

### ISSUE THREAD

**Issue by Wully616** [Cyanilux/URP_BlitRenderFeature#2]
Hi,

This feature works fine in mono rendering. But for Stereo rendering for VR it just draws a solid colour. 
I'm not sure if its a shader issue or not, but im using shader graph.
Unity 2019.4.21f1
URP 7.3.1

**Comment by Cyanilux** [comment]
I have no experience with VR so I'm afraid this isn't really something I can confirm or fix.

[This docs page](https://docs.unity3d.com/Manual/SinglePassStereoRendering.html) while more for the built-in RP, suggests that Graphics.Blit usually requires the texture to account for the texture tiling and offset (e.g. _MainTex_ST Vector4 property, Split into Vector2s into Tiling And Offset node, then into UV on Sample Texture 2D). I would assume the same applies to CommandBuffer.Blit and possibly with URP too, though this would cause the result to be stretched more than solid colour so it's possible there is another issue somewhere else too.

ScriptableRenderContext also has StartMultiEye(camera) and StopMultiEye(camera) which might be something to look into.

**Comment by Cyanilux** [comment]
For anyone interested in VR support, try cmd.DrawMesh or 2022.1 branches.

**Comment by BruceKristelijn** [comment]
Hi, would there be a solution I could implement in 2021? 2022 feels too unstable at the moment for us to use. Thanks!
