### ISSUE TITLE
Affecting Asset Previews (Prefabs, materials etc.) - URP 2D - 2022.3.15f1

### ISSUE THREAD

**Issue by EmreBeratKR** [Cyanilux/URP_BlitRenderFeature#20]
The feature works as intended but it has a side effect on how Unity Preview assets.

## Some Examples

Some of my prefabs:
<img width="443" alt="Screenshot 2024-04-04 at 12 09 02" src="https://github.com/Cyanilux/URP_BlitRenderFeature/assets/87636497/9e4eb92e-bf46-48c4-8921-cd9af243d0f3">

Some of my materials:
<img width="340" alt="Screenshot 2024-04-04 at 12 12 10" src="https://github.com/Cyanilux/URP_BlitRenderFeature/assets/87636497/f2f04fad-e4c5-4170-96a1-2bf203d03573">

The preview of the .fbx asset:
<img width="367" alt="Screenshot 2024-04-04 at 12 14 55" src="https://github.com/Cyanilux/URP_BlitRenderFeature/assets/87636497/7a7f6b9b-e821-490f-8b57-b1f20ff0d3c5">

The Main Preview window inside Shader Graph view:
![Screenshot 2024-04-04 at 12 17 47](https://github.com/Cyanilux/URP_BlitRenderFeature/assets/87636497/960d07cf-7503-46e2-bc42-b99a5efa4c1b)

**Comment by Cyanilux** [comment]
Ah yeah. Adding `if (renderingData.cameraData.isPreviewCamera) return;` to `AddRenderPasses` fixes it. Have updated all branches to include this.

**Comment by EmreBeratKR** [comment]
Wow, that was fast! Thanks for your help.

**Comment by EmreBeratKR** [comment]
I have tested the updated version. All of the previews are now fixed but the scene camera view still has the issue.

EDIT: It is working, I just have to uncheck the `Can Show In Scene View` which is default to `true`. This might be default to `false`.
