### ISSUE TITLE
Changing Blit material in run time

### ISSUE THREAD

**Issue by gsm041039** [Cyanilux/URP_BlitRenderFeature#5]
Hi, this feature is working fine on my project :)

but I want to ask if there have a way to change blit material in run time through script?
I am not familiar with scriptable render pipeline and I can't find any useful information about it.

It will be a big thanks if you can tell me about it!

**Comment by Cyanilux** [comment]
You can obtain a reference to the Blit feature by using a global field that you can set in the inspector.

```
public class Example : MonoBehaviour {

	public Blit blit;
	public Material newMaterial;

	public void Start() {
		blit.SetActive(true);
		blit.settings.blitMaterial = newMaterial;
	}
}
```
