### ISSUE TITLE
Blitting above an Overlay Camera

### ISSUE THREAD

**Issue by vncastanheira** [Cyanilux/URP_BlitRenderFeature#6]
Is there a way to apply the effect on top of everything, including a Canvas UI set to Overlay?

**Comment by Cyanilux** [comment]
If the "After Rendering" event doesn't already do that then probably not. You may need to use the Camera mode on the UI instead.

**Comment by vncastanheira** [comment]
Hmm, this seems like a general Unity limitation, even the built-in pipeline was like that.
I made a new Overlay camera only for the UI and it worked perfectly.
Thanks a lot for this render feature, it's really helpful! :D
