### ISSUE TITLE
Possibly broken on 2021.2.2f1, no output at all.

### ISSUE THREAD

**Issue by OctagonIsAnAmazingShape** [Cyanilux/URP_BlitRenderFeature#7]
On Unity 2021.2.2f1, the Blit feature does not work. Strangely, it seems to work in the preview window. I have seen this happen with the original blit feature and now it does not work anymore. Is there a fix to this?

**Comment by Cyanilux** [comment]
Thanks for letting me know. I've updated the feature (see master branch), should now work correctly in 2021.2. Let me know if there's any issues~
